test:
  three: aboba3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


organization-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8080
